info:
  contact: {}
  license: {}
paths:
  /api/v1/tags:
    post:
      parameters:
      - description: Name
        in: query
        name: name
        required: true
        type: string
      - description: State
        in: query
        name: state
        type: integer
      - description: CreateBy
        in: query
        name: created_by
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200, "data":{}, "msg":"ok"}'
          schema:
            type: string
      summary: 新增文章标签
  /api/v1/tags/:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200, "data":{}, "msg":"ok"}'
          schema:
            type: string
      summary: 获取多个文章标签
  /api/v1/tags/{id}:
    put:
      parameters:
      - description: ID
        in: query
        name: id
        required: true
        type: integer
      - description: ID
        in: query
        name: name
        required: true
        type: string
      - description: State
        in: query
        name: state
        type: integer
      - description: ModifiedBy
        in: query
        name: modified_by
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":"ok"}'
          schema:
            type: string
      summary: 修改文章标签
swagger: "2.0"
